services:
  - type: web
    name: financial-app-angola
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
